export const themes = [
  'Finance',
  'Marketing',
  'Healthcare',
  'Company',
  'Government',
  'Media',
  'BioTech',
  'Technology',
  'Legal',
  'Human Resources',
  'Business',
  'Energy/Construction/Manufacturing',
  'Retail',
  'Consumer Technology',
  'Events & Conferences',
];
export const categories = [
  'Accounting',
  'Ad Tech',
  'Administration',
  'Aerospace',
  'Agencies',
  'Agency/Dept',
  'Agriculture',
  'AgriTech',
  'Air Quality',
  'Analytics & Reporting',
  'APIs & Services',
  'Banking',
  'Benefits',
  'Bioproduction',
  'Branding',
  'Budgeting, Planning & Strategy',
  'Business Finance',
  'Business Services',
  'Business Solutions',
  'Business Structure',
  'Campaigns',
  'Certifications',
  'Channels & Types',
  'Chromatography',
  'Civil',
  'Clinical & Diagnostics',
  'Cloud',
  'Commodity',
  'Compliance & Governance',
  'Construction',
  'Consumer',
  'Content',
  'Contracts',
  'Controls & Standards',
  'Copyright',
  'Corporate Finance',
  'Creativity Software',
  'CRM',
  'Customer Service',
  'Data Center',
  'Data Management',
  'Database',
  'Demand Generation',
  'Desktop',
  'Device Connectivity',
  'Disease Control',
  'Dispute Resolution',
  'Diversity',
  'Document Management',
  'eCommerce',
  'Education',
  'Email',
  'Email Marketing',
  'Emerging Tech',
  'Employee Services',
  'Energy',
  'Energy & Construction',
  'Engineering',
  'Enterprise',
  'Entertainment',
  'Event Management',
  'Events & Conferences',
  'Expansion',
  'Finance',
  'Finance IT',
  'Financial',
  'Funding & Loans',
  'Gadgets',
  'Gaming',
  'Gaming Consoles',
  'General',
  'Government Regulations',
  'Hardware',
  'Health',
  'Health Insurance',
  'Health Tech',
  'HR',
  'HR Tech',
  'Immigration',
  'Instruments',
  'Insurance',
  'Intellectual Property',
  'IT Management',
  'Jail & Prison',
  'Lab Automation',
  'Lab Data Management & Analysis',
  'Labor',
  'Labor Relations',
  'Landmark Cases',
  'LawTech',
  'Leadership & Strategy',
  'Legal & Regulatory',
  'Legal Services',
  'Life Science',
  'Logistics',
  'Manufacturing',
  'Manufacturing & Supply Chain',
  'Marketing',
  'Mass Spectrometry',
  'Media & Advertising',
  'Medical Association',
  'Medical Education',
  'Medical Research',
  'Medical Specialty',
  'Medical Testing',
  'Medical Treatment',
  'Messaging',
  'Microbiology',
  'Mobile',
  'Monitoring',
  'Networking',
  'Operating System',
  'Operations',
  'Other',
  'Patient Management',
  'Payroll & Comp',
  'Performance',
  'Personal Computer',
  'Personal Finance',
  'Personal Protective Equipment (PPE)',
  'Place of Work',
  'Plasticware and Supplies',
  'Policy & Culture',
  'Printing',
  'Privacy',
  'Product Development & QA',
  'Productivity Software',
  'Professional Services',
  'Programming Languages',
  'Programs and Services',
  'Radiation Detection & Measurement',
  'Recruitment, Hiring & Onboarding',
  'Retail',
  'Retail Management',
  'Retail Technology',
  'Robotics',
  'Sales',
  'Search Engine',
  'Search Marketing',
  'Security',
  'Servers',
  'Smartphone',
  'Social',
  'Software Engineering',
  'Staff Administration',
  'Staff Departure',
  'Standards & Regulatory',
  'Storage',
  'Strategy & Analysis',
  'Supply Chain',
  'Tablets & Readers',
  'Taxation',
  'Technology',
  'Telecommunications',
  'Tools & Electronics',
  'Trade',
  'Trading & Investing',
  'Training & Development',
  'Transactions & Payments',
  'Translation & Language',
  'Transportation',
  'Trends',
  'Urban Planning',
  'Video',
  'Virtualization',
  'Water Quality',
  'Web',
  'Web Browser',
  'Website Publishing',
  'Wellness and Safety',
  'Wireless',
];
export const limitedTopics = [
  {
    Topic_ID: 1513393,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: '401k Audit',
    Description:
      "A 401(k) audit is a review of your company's 401(k) plan by a third-party accounting firm to ensure that the plan is within the guidelines and regulations set by both the IRS and the Department of Labor. The annual statutory audit of the financial accounts and providing an opinion on whether they are a true and fair reflection of the plan's financial position.",
  },
  {
    Topic_ID: 1502927,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Account Overdrafts',
    Description: 'Occurrence where money is withdrawn from a bank account and the available balance goes below zero.',
  },
  {
    Topic_ID: 1500797,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Account Reconciliation',
    Description: 'Accounting process that uses two sets of records to ensure figures are accurate and in agreement.',
  },
  {
    Topic_ID: 1342496,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounting',
    Description: 'Measurement, processing and communication of financial information about economic entities',
  },
  {
    Topic_ID: 1500799,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounting Audits',
    Description: 'Process by which an organizations accounts, books, records, and documents are checked for accuracy',
  },
  {
    Topic_ID: 1500800,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounting Automation',
    Description: 'Process by which accounting procedures and transformed form manual procedures into automatic procedures',
  },
  {
    Topic_ID: 1500802,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounting Compliance',
    Description: 'Meeting financial reporting requirements',
  },
  {
    Topic_ID: 1500803,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounting Consolidation',
    Description: 'Process of consolidating financial statements',
  },
  {
    Topic_ID: 1500806,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounting Journals Entries',
    Description: 'Record of accounting transactions',
  },
  {
    Topic_ID: 1500808,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounting Process',
    Description: 'Procedure by which transactions are identified, reconciled, and recorded',
  },
  {
    Topic_ID: 1506274,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounting Software',
    Description:
      'Accounting software describes a type of application software that records and processes accounting transactions within functional modules such as accounts payable, accounts receivable, journal, general ledger, payroll, and trial balance.',
  },
  {
    Topic_ID: 1507904,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounts Payable',
    Description: 'A business department or division that is responsible for making payments owed by the company to suppliers and other creditors.',
  },
  {
    Topic_ID: 1507905,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounts Receivable',
    Description: 'Accounts receivable, or receivables represent a line of credit extended by a company and normally have terms that require payments due within a relatively short time period, ranging from a few days to a fiscal or calendar year.',
  },
  {
    Topic_ID: 1342893,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounts Receivable / Accounts Payable',
    Description: 'Money owed to a company by its debtors/ Money owed by a company to its creditors',
  },
  {
    Topic_ID: 1506773,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Accounts Receivable Financing',
    Description: 'Accounts-receivable financing is a type of asset-financing arrangement in which a company uses its receivables outstanding invoices or money owed by customers to receive financing.',
  },
  {
    Topic_ID: 1342385,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Activity-Based Costing (ABC)',
    Description: 'Process of assigning product overhead costs to specific activities',
  },
  {
    Topic_ID: 1500811,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Allocation Entries',
    Description: 'Record of transfer of costs from a paying entity to a consuming entity',
  },
  {
    Topic_ID: 1503800,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'ASC 606: Revenue from Contracts with Customers',
    Description: 'ASC 606 is a revenue recognition standard and framework for recognizing revenue from contracts.',
  },
  {
    Topic_ID: 1515229,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Asset Classification',
    Description:
      'Asset Classification is a system for assigning assets into groups, based on a number of common characteristics. Various accounting rules are then applied to each asset group within the asset classification system, to properly account for each one.',
  },
  {
    Topic_ID: 1504702,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Audit Planning',
    Description:
      'Audit planning is a vital area of the audit primarily conducted at the beginning of audit process to ensure that appropriate attention is devoted to important areas, potential problems are promptly identified, work is completed expeditiously and work is properly coordinated.',
  },
  {
    Topic_ID: 1514569,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Audit Risk',
    Description:
      "Audit risk (also referred to as residual risk) refers to the risk that an auditor may issue an unqualified report due to the auditor's failure to detect material misstatement either due to error or fraud. Hence, audit risk is made up of two components â€“ risks of material misstatement and detection risk.",
  },
  {
    Topic_ID: 1506275,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Audit Trail',
    Description:
      'An audit trail (also called audit log) is a security-relevant chronological record, set of records, and/or destination and source of records that provide documentary evidence of the sequence of activities that have affected at any time a specific operation, procedure, or event.',
  },
  {
    Topic_ID: 1342194,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Audits',
    Description: 'Financial examinations of accounts',
  },
  {
    Topic_ID: 1508852,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Automated Invoice Processing',
    Description: 'Automated invoice processing helps to save a serious amount of time and money, compared with manual paper invoice processing, creating efficiencies and increasing the accuracy of captured data.',
  },
  {
    Topic_ID: 1508397,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Balance Sheet Reconciliation',
    Description:
      'Balance sheet reconciliation is the reconciliation of closing balances of all transactional and ledger entries and accounts forming part of the balance sheet items for a respective financial year and whether it is being recorded and properly classified making up to the balances appropriately in the balance sheet.',
  },
  {
    Topic_ID: 1504703,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Bank Reconciliation',
    Description: "A bank reconciliation is the process of matching the balances in an entity's accounting records for a cash account to the corresponding information on a bank statement.",
  },
  {
    Topic_ID: 1505674,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Capital Allowance',
    Description:
      'Capital allowances is the practice of allowing a company to get tax relief on tangible capital expenditure by allowing it to be expensed against its annual pre-tax income. Generally, the capital allowances will exist for only specified items of tangible capital expenditure, and the expensing is usually spread over a fixed period of years.',
  },
  {
    Topic_ID: 1504704,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Capital Expenditure',
    Description: 'Capital expenditure or capital expense (capex) is the money a company spends to buy, maintain, or improve its fixed assets, such as buildings, vehicles, equipment, or land.',
  },
  {
    Topic_ID: 1504385,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Client Accounting Services (CAS)',
    Description: 'Client Accounting Services (CAS) is a services model that provides automated technology and affordable accounting guidance.',
  },
  {
    Topic_ID: 1503812,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Cloud Accounting',
    Description: 'Cloud accounting software is similar to traditional, on-premises, or self-install accounting software, only theaccounting software is hosted on remote servers, similar to the SaaS (Software as a Service) business model.',
  },
  {
    Topic_ID: 1500816,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Committee of Sponsoring Organizations (COSO)',
    Description: 'Organization that aims to combat corporate fraud',
  },
  {
    Topic_ID: 1500817,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Company Audits',
    Description: "Financial examination of a company's accounts",
  },
  {
    Topic_ID: 1511059,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Cost Accounting',
    Description: "Cost accounting is a form of managerial accounting that aims to capture a company's total cost of production by assessing the variable costs of each step of production as well as fixed costs, such as a lease expense.",
  },
  {
    Topic_ID: 1506276,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Cost Allocation',
    Description:
      "Cost allocation is a process of providing relief to shared service organization's cost centers that provide a product or service. In turn, the associated expense is assigned to internal clients' cost centers that consume the products and services.",
  },
  {
    Topic_ID: 1501432,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Cost of Capital',
    Description: 'Opportunity cost of making an investment',
  },
  {
    Topic_ID: 1502928,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Cost of Goods Sold (COGS)',
    Description: 'Direct costs attributable to the production of the goods sold by a company.',
  },
  {
    Topic_ID: 1506277,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Cost Structure',
    Description:
      'Cost structure refers to the types and relative proportions of fixed and variable costs that a business incurs. The concept can be defined in smaller units, such as by product, service, product line, customer, division, or geographic region.',
  },
  {
    Topic_ID: 1514570,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Country by Country (CbC) Reporting',
    Description:
      'Country by Country (CbC) Reporting provides local tax authorities visibility to revenue, income, tax paid and accrued, employment, capital, retained earnings, tangible assets and activities. The purpose of CbC Reporting is to eliminate any gap in information between the taxpayers and tax administrations with regard to information on where the economic value is generated and whether it matches where profits are allocated and taxes are paid on a global level.',
  },
  {
    Topic_ID: 1500819,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Credit Card Reconciliations',
    Description: 'Process by which credit card transactions are reconciled',
  },
  {
    Topic_ID: 1500820,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Credit Derivatives',
    Description: 'Financial instrument used to sell the risk of loan default to a third party',
  },
  {
    Topic_ID: 1506278,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Credit Management',
    Description:
      "Credit management is the process of granting credit, the terms it's granted on and recovering this credit when it's due. This is the function within a bank or company to control credit policies that will improve revenues and reduce financial risks.",
  },
  {
    Topic_ID: 1504705,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Current Liabilities',
    Description: 'In accounting, current liabilities are often understood as all liabilities of the business that are to be settled in cash within the fiscal year or the operating cycle of a given firm, whichever period is longer.',
  },
  {
    Topic_ID: 1506279,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Days Sales Outstanding (DSO)',
    Description: 'Days sales outstanding (also called DSO and days receivables) is a calculation used by a company to estimate their average collection period.',
  },
  {
    Topic_ID: 1502929,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Distributed Ledgers',
    Description: 'A consensus of replicated, shared, and synchronized digital data geographically spread across multiple sites, countries, or institutions.',
  },
  {
    Topic_ID: 1505924,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Donor Management',
    Description: 'A Donor Management System or Nonprofit CRM is a means of organizing, analyzing, and strategically implementing communication strategies with nonprofit supporters to maintain and grow those relationships.',
  },
  {
    Topic_ID: 1503821,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Double-Entry Bookkeeping',
    Description: 'Double-Entry Bookkeeping, in accounting, is a system of bookkeeping so named because every entry to an account requires a corresponding and opposite entry to a different account.',
  },
  {
    Topic_ID: 1501171,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Ernst & Young',
    Description: 'Multinational accounting firm that provides assurance, tax, consulting, and advisory services.',
  },
  {
    Topic_ID: 1500814,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'External Audit',
    Description: "Performing the annual statutory audit of the financial accounts, providing an opinion on whether they are a true and fair reflection of the company's financial position.",
  },
  {
    Topic_ID: 1501172,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'FIFO Accounting (First In, First Out)',
    Description: 'Cost flow assumption that the first goods first added to inventory are assumed to be the first goods removed from inventory for sale',
  },
  {
    Topic_ID: 1506298,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Financial Accounting',
    Description: 'Financial accounting (or financial accountancy) is the field of accounting concerned with the summary, analysis and reporting of financial transactions pertaining to a business.',
  },
  {
    Topic_ID: 1342826,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'General Ledger',
    Description: 'Accounting record used to keep track of financial transactions',
  },
  {
    Topic_ID: 1503846,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Generally Accepted Accounting Principles (GAAP)',
    Description: 'Generally accepted accounting principles (GAAP) are a common set of accounting principles, standards and procedures that companies must follow when they compile their financial statements.',
  },
  {
    Topic_ID: 1506305,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Gross Margin',
    Description: 'Gross margin is the difference between revenue and cost of goods sold (COGS) divided by revenue. Gross margin is expressed as a percentage.',
  },
  {
    Topic_ID: 1504396,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Hedge Accounting',
    Description: 'Hedge accounting is a method of accounting where entries for the ownership of a security and the opposing hedge are treated as one.',
  },
  {
    Topic_ID: 1502930,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Income Statement',
    Description: "A financial statement of a company and shows the company's revenues and expenses during a particular period.",
  },
  {
    Topic_ID: 1500823,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Intercompany Accounting',
    Description: 'Process by which transactions are reconciled to eliminate duplication among departments',
  },
  {
    Topic_ID: 1505677,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Internal Audit',
    Description: "Internal auditing is an independent, objective assurance and consulting activity designed to add value and improve an organization's operations.",
  },
  {
    Topic_ID: 1503863,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'International Accounting Standards Board (IASB)',
    Description: 'The International Accounting Standards Board is the independent, accounting standard-setting body of the IFRS Foundation.',
  },
  {
    Topic_ID: 1500805,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'International Financial Reporting Standards (IFRS)',
    Description: 'A common global language for business affairs so that company accounts are understandable and comparable across international boundaries.',
  },
  {
    Topic_ID: 1506311,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Inventory Cost',
    Description: 'Inventory cost includes the costs to order and hold inventory, as well as to administer the related paperwork.',
  },
  {
    Topic_ID: 1502931,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Inventory Turnover',
    Description: 'A measure of the number of times inventory is sold or used in a time period such as a year.',
  },
  {
    Topic_ID: 1506312,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Invoice Processing',
    Description: 'Invoice processing involves the handling of incoming invoices from arrival to post. Invoices have many variations and types.',
  },
  {
    Topic_ID: 1507476,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Invoice Scanning',
    Description: 'Invoice scanning is the process where supplier invoices in different formats are scanned in order to digitize and capture the invoice information.',
  },
  {
    Topic_ID: 1508857,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Leasing Accounting',
    Description: 'Determining the accounting methodology of a lease with the two most common types being operating and financing (formerly  capital  ) leases.',
  },
  {
    Topic_ID: 1501174,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'LIFO Accounting (Last In, First Out)',
    Description: 'Cost flow assumption that goods last added to inventory are assumed to be the first goods removed from inventory for sale',
  },
  {
    Topic_ID: 1500827,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Multi-Currency Accounting',
    Description: 'Accounting that accommodates the use of multiple currencies',
  },
  {
    Topic_ID: 1502932,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Net Profit Margin',
    Description: 'The ration of net profits to revenues for a company or business segment.',
  },
  {
    Topic_ID: 1504706,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Operating Expense',
    Description:
      'An operating expense is an expense a business incurs through its normal business operations. Often abbreviated as OPEX, operating expenses include rent, equipment, inventory costs, marketing, payroll, insurance and funds allocated toward research and development.',
  },
  {
    Topic_ID: 1502933,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Operating Margin',
    Description: 'A measure of profitability indicating how much of each dollar of revenues is left over after both costs sold and operating expenses are considered.',
  },
  {
    Topic_ID: 1504707,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Opportunity Cost',
    Description: 'The opportunity cost, also known as alternative cost, is the value (not a benefit) of the choice of a best alternative cost while making a decision.',
  },
  {
    Topic_ID: 1504708,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Out of Pocket Cost',
    Description: 'In North American financial context an out-of-pocket expense (or out-of-pocket cost) is the direct outlay of cash that may or may not be later reimbursed from a third-party source.',
  },
  {
    Topic_ID: 1515310,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Outsourced Accounting',
    Description:
      'Outsourced accounting is the assigning of accounting, bookkeeping and/or compliance work to accounting professionals in another country. To do this, a business owner will partner with an outsourced accounting services provider, who will present him or her with qualified candidates.',
  },
  {
    Topic_ID: 1504710,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Payroll Expense',
    Description: 'Payroll expense is the amount of salaries and wages paid to employees in exchange for services rendered by them to a business.',
  },
  {
    Topic_ID: 1342616,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Project Accounting',
    Description: 'Process of creating financial reports for specific projects',
  },
  {
    Topic_ID: 1506314,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Purchase Order',
    Description: 'A purchase order (PO) is a commercial document and first official offer issued by a buyer to a seller, indicating types, quantities, and agreed prices for products or services.',
  },
  {
    Topic_ID: 1502934,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Quick Ratio (Acid-Test Ratio)',
    Description: 'A liquidity ratio that measures the ability of a company to pay its current liabilities when they come due with only quick assets.',
  },
  {
    Topic_ID: 1500830,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Recurring Journal Entries',
    Description: 'Journal entries recorded in every accounting period',
  },
  {
    Topic_ID: 1503853,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Revenue Recognition',
    Description: 'Revenue recognition is an accounting principle under generally accepted accounting principles (GAAP) that determines the specific conditions under which revenue is recognized or accounted for.',
  },
  {
    Topic_ID: 1503854,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Revenue Reporting',
    Description: 'Revenue reporting is the process of recording income.',
  },
  {
    Topic_ID: 1342108,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Small Business Accounting',
    Description: 'Measurement, processing and communication of financial information about small business entities',
  },
  {
    Topic_ID: 1500831,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Software as a Service (SaaS) Based Accounting',
    Description: 'Accounting software licensed using the SaaS model',
  },
  {
    Topic_ID: 1500833,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Suspense Accounts',
    Description: 'Accounts that have temporarily entered items that have not yet been allocated to the final account',
  },
  {
    Topic_ID: 1503723,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Sweep Account',
    Description: 'A sweep account is a bank account that automatically transfers amounts that exceed, or fall short of, a certain level into a higher interest-earning investment option at the close of each business day. ',
  },
  {
    Topic_ID: 1500834,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Tax Planning',
    Description: 'Analysis of a financial situation from a tax perspective',
  },
  {
    Topic_ID: 1504711,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Web Experience Management',
    Description: "Web Experience Management is a process of managing the all-round experience of the web user across various touch points in the journey through an organisation's web presence.",
  },
  {
    Topic_ID: 1502487,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Working Capital',
    Description: 'Business assets used in day-to-day operations',
  },
  {
    Topic_ID: 1504709,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Write Off',
    Description:
      'A write-off is a reduction of the recognized value of something. In accounting, this is a recognition of the reduced or zero value of an asset. In income tax statements, this is a reduction of taxable income, as a recognition of certain expenses required to produce the income.',
  },
  {
    Topic_ID: 1510456,
    Theme: 'Finance',
    Category: 'Accounting',
    Topic_Name: 'Zoho Books',
    Description: 'Zoho Books is online accounting software that manages your finances, automates business workflows, and helps you work collectively across departments. Zoho Books handles accounting tasks so users can focus on their business.',
  },
  {
    Topic_ID: 1505914,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Ad Blocking',
    Description:
      'Ad blocking or ad filtering is a type of software that can remove or alter advertising content from a webpage, website, or a mobile app. Ad blockers are available for a range of computer platforms, including desktop and laptop computers, tablet computers and smartphones.',
  },
  {
    Topic_ID: 1409076,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Ad Exchange',
    Description: 'A technology platform that facilitates the buying and selling of media advertising inventory from multiple ad networks',
  },
  {
    Topic_ID: 1503757,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Ad Fraud',
    Description: 'Ad fraud (also referred to as Invalid Traffic) is concerned with theory and practice of fraudulently representing online advertisement impressions, clicks, conversion or data events in order to generate revenue.',
  },
  {
    Topic_ID: 1503059,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Ad Networks',
    Description: 'A company that connects advertisers to web sites that want to host advertisements.',
  },
  {
    Topic_ID: 1503060,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Ad Servers',
    Description: 'The technology and service that places advertisements on web sites.',
  },
  {
    Topic_ID: 1503061,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Ad Verification',
    Description: "A process which attempts to verify that a campaign has executed according to the agency's or advertiser's choices and exclusions.",
  },
  {
    Topic_ID: 1503062,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Addressable TV Advertising',
    Description: 'Technologies that enable advertisers to selectively segment TV audiences and serve different ads or ad pods within a common program or navigation screen.',
  },
  {
    Topic_ID: 1506932,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Adobe Advertising Cloud',
    Description: 'Adobe Advertising Cloud, formerly Adobe Media Optimizer, is an independent, end-to-end platform for managing advertising across traditional TV and digital formats.',
  },
  {
    Topic_ID: 1505915,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'AdSense',
    Description: 'Google AdSense is a program run by Google that allows publishers in the Google Network of content sites to serve automatic text, image, video, or interactive media advertisements, that are targeted to site content and audience.',
  },
  {
    Topic_ID: 1351159,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'AdWords',
    Description: 'An online advertising service where advertisers pay to display brief advertising copy to web users',
  },
  {
    Topic_ID: 1409162,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Agency Trading Desk',
    Description: 'A massive media buyer and re-seller, which functions as an independent working unit within a large media buying concern',
  },
  {
    Topic_ID: 1505605,
    Theme: 'Marketing',
    Category: 'Ad Tech',
    Topic_Name: 'Amazon Marketing Services (AMS)',
    Description: 'Amazon Marketing Services (AMS) offers effective tools to help vendors stand out against their competitors and drive traffic to product detail pages and branded pages.',
  },
];
