import graniteForm from '../../granite/form/graniteForm';
import graniteMultiSelect from '../../granite/plugins/form/multiSelect/graniteMultiSelect';
import relevantTopics from '../../granite/plugins/form/topicSelectors/relevantTopics';

import '../../granite/form/graniteForm.css';
import '../../granite/plugins/form/multiSelect/graniteMultiSelect.css';
import '../../granite/plugins/form/topicSelectors/topicSelectors.css';
const industriesObj = [
  { industry: 'Select All Industries' },
  { industry: 'Agriculture', sub_industries: ['Agriculture', 'Agriculture - Animals & Livestock', 'Agriculture - Crops', 'Agriculture - Forestry'] },
  {
    industry: 'Business Services',
    sub_industries: [
      'Business Services',
      'Business Services - Accounting',
      'Business Services - Advertising & Marketing',
      'Business Services - Commercial Printing',
      'Business Services - Graphic Design',
      'Business Services - HR & Recruiting',
      'Business Services - Import/Export',
      'Business Services - Management Consulting',
      'Business Services - Waste Management',
    ],
  },
  {
    industry: 'Construction',
    sub_industries: ['Construction', 'Construction - Architecture', 'Construction - Commercial Building', 'Construction - Contractors', 'Construction - Heavy Construction', 'Construction - Residential Building'],
  },
  {
    industry: 'Consumer Services',
    sub_industries: [
      'Consumer Services',
      'Consumer Services - Auto Repair',
      'Consumer Services - Car Rental',
      'Consumer Services - Laundry & Dry Cleaning',
      'Consumer Services - Non-Auto Repair',
      'Consumer Services - Veterinary',
      'Consumer Services - Weight Health Management',
    ],
  },
  {
    industry: 'Cultural',
    sub_industries: ['Cultural', 'Cultural - Libraries', 'Cultural - Museums & Art Galleries', 'Cultural - Performance Arts'],
  },
  {
    industry: 'Education',
    sub_industries: ['Education', 'Education - Colleges & Universities', 'Education - K-12 Schools', 'Education - Professional, Technical & Trade Schools'],
  },
  {
    industry: 'Energy, Utilities & Waste',
    sub_industries: ['Energy, Utilities & Waste', 'Energy, Utilities & Waste - Energy', 'Energy, Utilities & Waste - Utilities', 'Energy, Utilities & Waste - Waste Treatment'],
  },
  {
    industry: 'Finance',
    sub_industries: [
      'Finance',
      'Finance - Banking',
      'Finance - Credit Card Transaction Processing',
      'Finance - Investment Banking',
      'Finance - Portfolio Management & Financial Advice',
      'Finance - Trade & Development',
      'Finance - Venture Capital Private Equity & Fund Raising',
    ],
  },
  {
    industry: 'Gaming',
    sub_industries: ['Gaming'],
  },
  {
    industry: 'Government',
    sub_industries: ['Government', 'Government - Federal', 'Government - Public Safety', 'Government - State & Province', 'Government - Towns, Cities & Municipalities'],
  },
  {
    industry: 'Healthcare',
    sub_industries: ['Healthcare', 'Healthcare - Hospitals & Clinics', 'Healthcare - Medical Offices', 'Healthcare - Pharmaceuticals'],
  },
  {
    industry: 'Hospitality & Hotels',
    sub_industries: ['Hospitality & Hotels', 'Hospitality & Hotels - Lodging & Resorts', 'Hospitality & Hotels - Restaurants'],
  },
  {
    industry: 'Insurance',
    sub_industries: ['Insurance', 'Insurance - Accident & Health', 'Insurance - Property & Casualty'],
  },
  {
    industry: 'Legal',
    sub_industries: ['Legal'],
  },
  {
    industry: 'Manufacturing',
    sub_industries: [
      'Manufacturing',
      'Manufacturing- Aerospace & Defense',
      'Manufacturing - Automobile',
      'Manufacturing - Boats & Marine',
      'Manufacturing - Building Materials',
      'Manufacturing - Chemicals & Gases',
      'Manufacturing - Computer Equipment',
      'Manufacturing - Consumer Goods',
      'Manufacturing - Electronics',
      'Manufacturing - Food & Beverage',
      'Manufacturing - Furniture',
      'Manufacturing - Industrial Engineering',
      'Manufacturing - Machinery',
      'Manufacturing - Metals & Mining',
      'Manufacturing - Plastics, Synthetics & Rubber',
      'Manufacturing - Semiconductors',
      'Manufacturing - Textiles & Apparel',
      'Manufacturing - Wood & Paper Products',
    ],
  },
  {
    industry: 'Media & Internet',
    sub_industries: [
      'Media & Internet',
      'Media & Internet - Info Collection & Delivery',
      'Media & Internet - Media Broadcasting',
      'Media & Internet - Movie & Video',
      'Media & Internet - Music',
      'Media & Internet - Newspapers & News Services',
      'Media & Internet - Publishing',
      'Media & Internet - Search Engines & Internet Portals',
    ],
  },
  {
    industry: 'Military',
    sub_industries: ['Military'],
  },
  {
    industry: 'Non-Profit',
    sub_industries: ['Non-Profit'],
  },
  {
    industry: 'Real Estate',
    sub_industries: ['Real Estate', 'Real Estate - Commercial', 'Real Estate - Residential'],
  },
  {
    industry: 'Recreation',
    sub_industries: ['Recreation'],
  },
  {
    industry: 'Resource Extraction',
    sub_industries: ['Resource Extraction', 'Resource Extraction - Metals & Mining', 'Resource Extraction - Oil & Gas'],
  },
  {
    industry: 'Retail',
    sub_industries: [
      'Retail',
      'Retail - Apparel & Fashion',
      'Retail - Consumer Electronics',
      'Retail - Department Stores & Super Stores',
      'Retail - Drug Stores & Pharmacies',
      'Retail - eCommerce',
      'Retail - Furniture',
      'Retail - Gas Stations & Convenience',
      'Retail - Grocery',
      'Retail - Home Improvement & Hardware',
      'Retail - Jewelry',
      'Retail - Motor Vehicles',
      'Retail - Office Products',
      'Retail - Pet Products',
    ],
  },
  {
    industry: 'Software',
    sub_industries: ['Software', 'Software - Business Intelligence', 'Software - Database & File Management', 'Software - Financial/Legal/HR', 'Software - Healthcare', 'Software - Security'],
  },
  {
    industry: 'Sports',
    sub_industries: ['Sports'],
  },
  {
    industry: 'Telecommunications',
    sub_industries: ['Telecommunications', 'Telecommunications - Cable & Satellite', 'Telecommunications - ISPs', 'Telecommunications - Telephony & Wireless'],
  },
  {
    industry: 'Transportation & Travel',
    sub_industries: [
      'Transportation & Travel',
      'Transportation & Travel - Aviation & Aerospace',
      'Transportation & Travel - Marine Shipping',
      'Transportation & Travel - Transit & Non-Aviation Passengers',
      'Transportation & Travel - Travel Agencies & Reservation Services',
      'Transportation & Travel - Trucking & Logistics',
      'Transportation & Travel - Warehousing',
    ],
  },
  {
    industry: 'Wholesalers',
    sub_industries: ['Wholesalers', 'Wholesalers - Durable Goods', 'Wholesalers - Non-Durable Goods'],
  },
];

const countryList = [
  'All Locations',
  'United States',
  'Afghanistan',
  'Aland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Cote Divoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'France, Metropolitan',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard and McDonald Islands',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iraq',
  'Ireland',
  'Islamic Republic of Iran',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea (North)',
  'Korea (South)',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'S. Georgia and S. Sandwich Islands',
  'Saint Lucia',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'St. Helena',
  'St. Kitts and Nevis',
  'St. Pierre and Miquelon',
  "St. Vincent's & Grenadines",
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen Islands',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom (Great Britain)',
  'United States',
  'United States Minor Outlying Islands',
  'United States Virgin Islands',
  'Uruguay',
  'USSR (former)',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City State',
  'Venezuela',
  'Vietnam',
  'Wallis And Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Zaire',
  'Zambia',
  'Zimbabwe',
];
const regionList = ['All Regions', 'Asia', 'Caribbean', 'Central America', 'Europe', 'North America', 'Oceania', 'South America', 'Africa'];
const industriesList = [
  'All Industries',
  'Agriculture',
  'Agriculture - Animals & Livestock',
  'Agriculture - Crops',
  'Agriculture - Forestry',
  'Business Services',
  'Business Services - Accounting',
  'Business Services - Advertising & Marketing',
  'Business Services - Commercial Printing',
  'Business Services - Graphic Design',
  'Business Services - HR & Recruiting',
  'Business Services - Import/Export',
  'Business Services - Management Consulting',
  'Business Services - Waste Management',
  'Construction',
  'Construction - Architecture',
  'Construction - Commercial Building',
  'Construction - Contractors',
  'Construction - Heavy Construction',
  'Construction - Residential Building',
  'Consumer Services',
  'Consumer Services - Auto Repair',
  'Consumer Services - Car Rental',
  'Consumer Services - Laundry & Dry Cleaning',
  'Consumer Services - Non-Auto Repair',
  'Consumer Services - Veterinary',
  'Consumer Services - Weight Health Management',
  'Cultural',
  'Cultural - Libraries',
  'Cultural - Museums & Art Galleries',
  'Cultural - Performance Arts',
  'Education',
  'Education - Colleges & Universities',
  'Education - K-12 Schools',
  'Education - Professional, Technical & Trade Schools',
  'Energy, Utilities & Waste',
  'Energy, Utilities & Waste - Energy',
  'Energy, Utilities & Waste - Utilities',
  'Energy, Utilities & Waste - Waste Treatment',
  'Finance',
  'Finance - Banking',
  'Finance - Credit Card Transaction Processing',
  'Finance - Investment Banking',
  'Finance - Portfolio Management & Financial Advice',
  'Finance - Trade & Development',
  'Finance - Venture Capital Private Equity & Fund Raising',
  'Gaming',
  'Government',
  'Government - Federal',
  'Government - Public Safety',
  'Government - State & Province',
  'Government - Towns, Cities & Municipalities',
  'Healthcare',
  'Healthcare - Hospitals & Clinics',
  'Healthcare - Medical Offices',
  'Healthcare - Pharmaceuticals',
  'Hospitality & Hotels',
  'Hospitality & Hotels - Lodging & Resorts',
  'Hospitality & Hotels - Restaurants',
  'Insurance',
  'Insurance - Accident & Health',
  'Insurance - Property & Casualty',
  'Legal',
  'Manufacturing',
  'Manufacturing- Aerospace & Defense',
  'Manufacturing - Automobile',
  'Manufacturing - Boats & Marine',
  'Manufacturing - Building Materials',
  'Manufacturing - Chemicals & Gases',
  'Manufacturing - Computer Equipment',
  'Manufacturing - Consumer Goods',
  'Manufacturing - Electronics',
  'Manufacturing - Food & Beverage',
  'Manufacturing - Furniture',
  'Manufacturing - Industrial Engineering',
  'Manufacturing - Machinery',
  'Manufacturing - Metals & Mining',
  'Manufacturing - Plastics, Synthetics & Rubber',
  'Manufacturing - Semiconductors',
  'Manufacturing - Textiles & Apparel',
  'Manufacturing - Wood & Paper Products',
  'Media & Internet',
  'Media & Internet - Info Collection & Delivery',
  'Media & Internet - Media Broadcasting',
  'Media & Internet - Movie & Video',
  'Media & Internet - Music',
  'Media & Internet - Newspapers & News Services',
  'Media & Internet - Publishing',
  'Media & Internet - Search Engines & Internet Portals',
  'Military',
  'Non-Profit',
  'Real Estate',
  'Real Estate - Commercial',
  'Real Estate - Residential',
  'Recreation',
  'Resource Extraction',
  'Resource Extraction - Metals & Mining',
  'Resource Extraction - Oil & Gas',
  'Retail',
  'Retail - Apparel & Fashion',
  'Retail - Consumer Electronics',
  'Retail - Department Stores & Super Stores',
  'Retail - Drug Stores & Pharmacies',
  'Retail - eCommerce',
  'Retail - Furniture',
  'Retail - Gas Stations & Convenience',
  'Retail - Grocery',
  'Retail - Home Improvement & Hardware',
  'Retail - Jewelry',
  'Retail - Motor Vehicles',
  'Retail - Office Products',
  'Retail - Pet Products',
  'Software',
  'Software - Business Intelligence',
  'Software - Database & File Management',
  'Software - Financial/Legal/HR',
  'Software - Healthcare',
  'Software - Security',
  'Sports',
  'Telecommunications',
  'Telecommunications - Cable & Satellite',
  'Telecommunications - ISPs',
  'Telecommunications - Telephony & Wireless',
  'Transportation & Travel',
  'Transportation & Travel - Aviation & Aerospace',
  'Transportation & Travel - Marine Shipping',
  'Transportation & Travel - Transit & Non-Aviation Passengers',
  'Transportation & Travel - Travel Agencies & Reservation Services',
  'Transportation & Travel - Trucking & Logistics',
  'Transportation & Travel - Warehousing',
  'Wholesalers',
  'Wholesalers - Durable Goods',
  'Wholesalers - Non-Durable Goods',
];
const roles = ['Accounting', 'Customer Success', 'Engineering', 'Executive Leadership', 'Finance', 'HR', 'IT', 'Marketing', 'Operations', 'Product', 'Sales'];
const jsonBlock = {
  id: 'form__field-demo',
  options: {
    title: '',
    step_form: false,
    edit_form: false,
    addapptation_action: '/score',
    description: '',
    title_font_size: '40px',
    position_form: 'center',
    description_font_size: '20px',
    db_action: '',
    db_object: '',
    db_id: '',
    db_redirect: '',
    flash_message: '',
    form_id: '',
    button_1_label: '',
    button_1_href: '',
    submit_label: 'Submit',
    submit_classes: 'g__btn g__btn-primary',
    cancel_label: 'Cancel',
    max_width: '',
    enctype: 'application/x-www-form-urlencoded',
    method: 'POST',
    visibility_settings: '',
    hide_submit: false,
    allow_cancel: false,
    default_picklists: true,
  },
  records: [
    // {
    //   id: 'bombora-topics',
    //   name: 'bombora-topics',
    //   title: "Competitors You Want to Track<br><span class='g__select-all' style='color:#757575;'>(these will appear as competitive signals in your results)</span>",
    //   type: 'custom',
    //   custom_function: graniteMultiSelect('Competitive_Topics__c'),
    //   required: false,
    //   value: '',
    //   classes: '',
    // },
    {
      id: 'bombora-topics',
      name: 'bombora-topics',
      title: '',
      type: 'custom',
      custom_function: relevantTopics(),
      required: false,
      value: '',
      classes: '',
    },
  ],
};
graniteForm(jsonBlock);

// const jsonBlock = {
//   id: "form__field-demo",
//   options: {
//     title: "",
//     step_form: false,
//     edit_form: false,
//     addapptation_action: "/score",
//     description: "",
//     title_font_size: "40px",
//     position_form: "center",
//     description_font_size: "20px",
//     db_action: "",
//     db_object: "",
//     db_id: "",
//     db_redirect: "",
//     flash_message: "",
//     form_id: "",
//     button_1_label: "",
//     button_1_href: "",
//     submit_label: "Submit",
//     submit_classes: "g__btn g__btn-primary",
//     cancel_label: "Cancel",
//     max_width: "",
//     enctype: "application/x-www-form-urlencoded",
//     method: "POST",
//     visibility_settings: "",
//     hide_submit: false,
//     allow_cancel: false,
//     default_picklists: true,
//   },
//   records: [
//     {
//       id: "checkbox-demo",
//       name: "checkbox-demo",
//       title: "Checkbox Demo",
//       type: "checkbox",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "color-demo",
//       name: "color-demo",
//       title: "Color",
//       type: "color",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "currency-demo",
//       name: "currency-demo",
//       title: "Currency",
//       type: "currency",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "bombora-topics",
//       name: "bombora-topics",
//       title: "What competitive topics would you like to track?",
//       type: "custom",
//       custom_function: graniteMultiSelect("Competitive_Topics__c"),
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "bombora-topics",
//       name: "bombora-topics",
//       title: "What adjacent topics would you like to track?",
//       type: "custom",
//       custom_function: graniteMultiSelect("adjacent-topics"),
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "date-demo",
//       name: "date-demo",
//       title: "Date",
//       type: "date",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "email-demo",
//       name: "email-demo",
//       title: "Email",
//       type: "email",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "file-demo",
//       name: "file-demo",
//       title: "File",
//       type: "file",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     // {
//     //   type: "picklist",
//     //   id: "multiselect-demo",
//     //   name: "multiselect-demo",
//     //   title: "Multiselect",
//     //   required: true,
//     //   multiple: true,
//     //   options: [
//     //     "Finance",
//     //     "Education",
//     //     "Software",
//     //     "Manufacturing",
//     //     "Technology",
//     //     "Option 3",
//     //     "Option 4",
//     //   ],
//     //   value: "",
//     //   placeholder: "",
//     //   classes: "g__form-width-50",
//     // },
//     {
//       id: "number-demo",
//       name: "number-demo",
//       title: "Number",
//       type: "number",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "password-demo",
//       name: "password-demo",
//       title: "Password",
//       type: "password",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "picklist-demo",
//       name: "picklist-demo",
//       title: "Picklist",
//       type: "picklist",
//       options: [
//         ["option-1", "Option 1"],
//         ["option-2", "Option 2"],
//         ["option-3", "Option 3"],
//       ],
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "radio-demo",
//       name: "radio-demo",
//       title: "Radio",
//       type: "radio",
//       options: [
//         ["option-1", "Option 1"],
//         ["option-2", "Option 2"],
//         ["option-3", "Option 3"],
//       ],
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "range-demo",
//       name: "range-demo",
//       title: "Range",
//       type: "range",
//       min: 0,
//       max: 100,
//       required: false,
//       value: "30",
//       classes: "",
//     },
//     {
//       type: "tags",
//       label: "tags",
//       title: "Tags",
//       id: "tags-demo",
//       name: "tags-demo",
//       required: true,
//       options: "",
//       value: "",
//       placeholder: "",
//       classes: "",
//     },
//     {
//       id: "tel-demo",
//       name: "tel-demo",
//       title: "Telephone",
//       type: "tel",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "textarea-demo",
//       name: "textarea-demo",
//       title: "Textarea",
//       type: "textarea",
//       required: false,
//       value: "",
//       classes: "",
//     },
//     {
//       id: "text-demo",
//       name: "text-demo",
//       title: "Text",
//       type: "text",
//       required: false,
//       value: "",
//       classes: "",
//     },
//   ],
// };

// graniteForm(jsonBlock);
